### ISSUE TITLE
Draw ER model for Users, Posts and Comments

### ISSUE THREAD

**Issue by JoachimFavre** [ProximaEPFL/proxima#16]
The firebase database must contain data that allows:
- User information (unique username, pseudo, join date, Centauri points)
- Post information (title, description, localisation, owner, publication date, upvote score)
- Get all posts from a user
- Get nearby posts to a position
- Users can upvote/downvote post (they cannot upvote the same post twice)
- Comment information (user, publication date, upvote score)
- Users can read/add comments to a post (only a depth of 1 for now).

**Comment by JoachimFavre** [comment]
Here is the ER we came up with:
![Image](https://github.com/ProximaEPFL/proxima/assets/22430066/492cd28e-12ba-491c-88ef-560c5fc821ff)

This yields that we have 2 collections in Firestore:
- `User`
- `Publishable`, that contains both `Post`s and `Comment`s, so that it is impossible a `Post` and a `Comment` have the same key. It needs an extra attribute to be able to differentiate between the two.

The relations can be defined as:
- `Published`: Any `Publishable` stores a reference to the `uid` of the `User` who published it.
- `Commented`: Any `Comment` stores a reference to the `pid` of the `Publishable` it comments.
- `VotedOn`: Each `User` has a sub-collection which stores a reference to the `pid` of the `Publishable` they voted on, and whether it was an upvote or a downvote. The upvote score and this sub-collection are updated atomically in the same transaction when the user wants to modify their vote.

Note that, to handle positions, we can use [geohashes](https://firebase.google.com/docs/firestore/solutions/geoqueries). This will make us slightly more data than required from the database, but this is nice since it will allow us to cache the data and decrease the number of requests we make to Firebase.

**Comment by gruvw** [comment]
I am not sure about the `Publishable` interface. I think a post should not be under the same class as a comment as they do not follow an `is a` directive.
Posts and Comments are two different types of objects we store.
Posts have a geopos associated, but comments do not for instance.

Otherwise, it looks promising :)

**Comment by JoachimFavre** [comment]
After some though, maybe it is hard to use aggregation (in the ER diagram sense) in Firestore. I have this other ER as a proposal:

![Image](https://github.com/ProximaEPFL/proxima/assets/22430066/a624818e-4c9d-4505-ba5b-48075604dab1)

This yields 3 collections in Firestore:
- `User`
- `Post`
- `Comment` (that are both comments on posts and comments on comments at any depth).

The relations can be defined as:
- `Published`: Any `Post` stores a reference to the `uid` of the `User` who published it.
- `CommentedPost` and `CommentedComment`: `Comment`s store a reference to the user who published it. Moreover, any `Post` stores a sub-collection of reference to its direct comments `cid`. Any `Comment` stores a list of reference to its direct comments `cid`. Those relations are a bit weid on the ER diagram since any comment is in `CommentedPost` xor `CommentedComment`. Note that, whereas `Post`s store the comment data as a sub-collection, `Comment`s don't. This allows to fetch the posts more quickly when making the feed (we don't need the comments then), but do less queries when construct the comment tree.
- `VotedOnPost`: Each User has a sub-collection which stores a reference to the `pid` of the `Post`s they voted on, and whether it was an upvote or a downvote. The upvote score and this sub-collection are updated atomically in the same transaction when the user wants to modify their vote.
- `VotedOnComment` works the same as `VotedOnPost`.

Note that we need to split the case where the user voted on a post or a comment, because there might exist a post and a comment that have the same id in this model.

**Comment by yoannLafore** [comment]
This looks good to me to manage the various layers of comments.
I just think that you forgot to include the comment content in the ER model.

**Comment by gruvw** [comment]
Yeah I think it is better now :) good job

**Comment by yoannLafore** [comment]
After giving another though about it, I think that we can make the following small modification to optimize the firestore implementation:
Instead of having a `Comment` root collection, we can have a `Comment` collection nested in each post (that contains all the layers of comments for a post).
This way, we better separate the comments of different posts.

Also, this makes deleting a post easier as its comments are nested in it.
Regarding the performance issues of querying the comments in the nested collection, the nested level has apparently no effect on the querying performance according to :
https://stackoverflow.com/questions/57100953/does-affect-deep-nested-collection-on-performance-cloud-firestore

**Comment by JoachimFavre** [comment]
In the post you shared, they mention [queries scale with the size of your result set, not the size of your data set](https://stackoverflow.com/q/46603205). Therefore, what would be the improvements of your method?

**Comment by yoannLafore** [comment]
I think that the main benefit is that because `Post` are directly linked to their `Comments`  (through nested collection), it makes the firestore structure more intuitive and potentialy easier to work with in the future for the same performance.

For example, assuming that we will end up using firebase Cloud Function in our project (which is likely):
The post deletion process will be much easier because we will be able to use recursive deletion given by firebase.


With nested comments:
We can use a recursive delete:
```javascript
    await firebase_tools.firestore
      .delete(db.collection("posts").doc("post_id"), {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        force: true,
        token: functions.config().fb.token
      });
``` 
[source](https://firebase.google.com/docs/firestore/solutions/delete-collections?hl=fr#:~:text=%C2%A0%20%C2%A0%20await%20firebase_tools.firestore%0A%C2%A0%20%C2%A0%20%C2%A0%20.delete(path%2C%20%7B%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20project%3A%20process.env.GCLOUD_PROJECT%2C%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20recursive%3A%20true%2C%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20force%3A%20true%2C%0A%C2%A0%20%C2%A0%20%C2%A0%20%C2%A0%20token%3A%20functions.config().fb.token%0A%C2%A0%20%C2%A0%20%C2%A0%20%7D)%3B)



Without nested comments:

We need to retrieve manually all the comments of a post in the root `Comment` collection and then proceed to the deletion.
- Thus concretly, we first need to query the comment reference collection in the post to get the direct comments.
- Then we need to traverse the tree of comments in order to know which ones need to be deleted. (the tree traversal might require a lot of queries)
- Finally we must proceed to the deletion of all the retrieved comments. 

And for each step, we must implement a batch system to avoid overwhelming.
